{application,ypages,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,crypto,ssl]},
              {mod,{ypages_app,[]}},
              {env,[]},
              {modules,[ypages_app,ypages_fbdata,ypages_request,ypages_riak,
                        ypages_sup,ypages_urls,ypages_util]}]}.
